export default {
  title: 'RSS Virtual Keyboard',
  upperCase: true,
};
export const keyboard = {
  line_1: [
    { char: '`', alt: '~', color: 'dark' },
    { char: '1', alt: '!', color: 'light' },
    { char: '2', alt: '@', color: 'light' },
    { char: '3', alt: '#', color: 'light' },
    { char: '4', alt: '$', color: 'light' },
    { char: '5', alt: '%', color: 'light' },
    { char: '6', alt: ':', color: 'light' },
    { char: '7', alt: '?', color: 'light' },
    { char: '8', alt: '*', color: 'light' },
    { char: '9', alt: '(', color: 'light' },
    { char: '0', alt: ')', color: 'light' },
    { char: '-', alt: '_', color: 'light' },
    { char: '=', alt: '+', color: 'light' },
    { char: 'Backspace', color: 'dark' },
  ],
  line_2: [
    { char: 'Tab', color: 'dark' },
    { char: 'Q', color: 'light', alt: 'q' },
    { char: 'W', color: 'light', alt: 'w' },
    { char: 'E', color: 'light', alt: 'e' },
    { char: 'R', color: 'light', alt: 'r' },
    { char: 'T', color: 'light', alt: 't' },
    { char: 'Y', color: 'light', alt: 'y' },
    { char: 'U', color: 'light', alt: 'u' },
    { char: 'I', color: 'light', alt: 'i' },
    { char: 'O', color: 'light', alt: 'o' },
    { char: 'P', color: 'light', alt: 'p' },
    { char: '[', color: 'light', alt: '{' },
    { char: ']', color: 'light', alt: '}' },
    {
      char: '\\', alr: '/', color: 'light', alt: '/',
    },
    { char: 'DEL', color: 'dark' },
  ],
  line_3: [
    { char: 'Caps Lock', color: 'dark' },
    { char: 'A', color: 'light', alt: 'a' },
    { char: 'S', color: 'light', alt: 's' },
    { char: 'D', color: 'light', alt: 'd' },
    { char: 'F', color: 'light', alt: 'f' },
    { char: 'G', color: 'light', alt: 'g' },
    { char: 'H', color: 'light', alt: 'h' },
    { char: 'J', color: 'light', alt: 'j' },
    { char: 'K', color: 'light', alt: 'k' },
    { char: 'L', color: 'light', alt: 'l' },
    { char: ';', color: 'light', alt: ':' },
    { char: '\'', color: 'light', alt: '\'' },
    { char: 'ENTER', color: 'dark' },
  ],
  line_4: [
    { char: 'Shift', color: 'dark' },
    { char: '\\', color: 'light', alt: '|' },
    { char: 'Z', color: 'light', alt: 'z' },
    { char: 'X', color: 'light', alt: 'x' },
    { char: 'C', color: 'light', alt: 'c' },
    { char: 'V', color: 'light', alt: 'v' },
    { char: 'B', color: 'light', alt: 'b' },
    { char: 'N', color: 'light', alt: 'n' },
    { char: 'M', color: 'light', alt: 'm' },
    { char: ',', color: 'light', alt: '<' },
    { char: '.', color: 'light', alt: '>' },
    { char: '/', color: 'light', alt: '?' },
    { char: '&uarr;', color: 'dark', type: 'arrow' },
    { char: 'Shift', color: 'dark', type: 'right_shift' },
  ],
  line_5: [
    { char: 'Ctrl', color: 'dark' },
    { char: 'Win', color: 'dark' },
    { char: 'Alt', color: 'dark' },
    { char: ' ', color: 'light', type: 'spacebar' },
    { char: 'Alt', color: 'dark' },
    { char: 'Ctrl', color: 'dark' },
    { char: '&larr;', color: 'dark', type: 'arrow' },
    { char: '&darr;', color: 'dark', type: 'arrow' },
    { char: '&rarr;', color: 'dark', type: 'arrow' },
  ],
};
